config/routes.rb
Rails.application.routes.draw do
  root to: 'users/homes#top'

  # デバイスのURL
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get '/users/sign_in' => 'users/sessions#new'
    post '/users/sign_in' => 'users/sessions#create'
    delete '/users/sign_out' => 'users/sessions#destroy'
    get '/users/sign_up' => 'users/registrations#new'
    get '/users/passwords/edit' => 'users/registrations#edit'
    patch '/users/passwords/update' => 'users/registrations#update'
    post '/users/sign_up' => 'users/registrations#create'
    get '/users/' => 'users/passwords#edit'
    patch '/users/passwords' => 'users/passwords#update'
    get '/users/passwords/new' => 'users/passwords#new'
  end

  # ユーザー側のURL
  namespace :users do
    resource :passwords, only: [:create, :update]
    get 'homes/about' => 'homes#about'
    get 'homes/my_page' => 'homes#my_page'
    get 'homes/guidance' => 'homes#guidance'
    resource :users, only: [:show, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :youtube, only: [:index, :create, :destroy]
    resources :notes, only: [:index, :edit, :create, :destroy, :update]
    resources :notices, only: [:index, :show]
    get '/users/youtube' => '/users/youtube#favorite'
    resources :posts do
      resources :comments, only: [:create, :destroy] do
        resource :answers, only: [:create, :destroy]
      end
      resource :favorites, only: [:create, :destroy]
    end
    get '/users/posts' => '/users/posts#search'
  end

  # 管理者側のURL
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'

    authenticated :admin do
      delete '/admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
      get 'admins/password/edit' => 'admins/passwords#edit', as: 'edit_admin_password'
      patch 'admins/password' => 'admins/passwords#update', as: 'admin_password'
      get 'admins/passwords/new' => 'admins/password#new', as: 'admin_forgot_password'
    end
  end

  namespace :admins do
    resource :admins, only: [:show, :edit]
    resources :users, only: [:index, :edit, :destroy, :update]
    resources :posts, only: [:index, :edit, :destroy, :update]
    resources :contacts, only: [:index, :show, :destroy, :update]
    resources :notices, only: [:index, :edit, :update, :destroy, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :user_information, only: [:edit, :update, :destroy]

  def index
    @users = User.recent.page(params[:page]).per(20).search(params[:name])
  end

  def edit
  end

  def update
    @user.update(user_params) ? redirect_to(admins_users_path) : render(:edit)
  end

  def destroy
    @user.destroy ? redirect_to(admins_users_path) : render(:index)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def user_information
    @user = User.find(params[:id])
  end
end

app/controllers/users/answers_controller.rb
class Users::AnswersController < ApplicationController
  # good_answer作成
  def create
    comment = Comment.find(params[:comment_id])
    @answer = Answer.new(comment_id: params[:comment_id], user_id: comment.user.id)
    if @answer.save
      user = User.find(comment.user.id)
      user.update(answer_point: user.answer_point += 1)
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  # good_answer消去
  def destroy
    comment = Comment.find(params[:comment_id])
    if Answer.find_by(comment_id: params[:comment_id], user_id: comment.user_id)
      @answer = Answer.find_by(comment_id: params[:comment_id], user_id: comment.user_id)
      @answer.destroy
      user = User.find(comment.user.id)
      user.update(answer_point: user.answer_point -= 1)
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  # コメント生成
  def create
    post = Post.find(params[:post_id])
    @user = post.user
    @comment = post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:primary] = 'コメント投稿を投稿しました'
      NotificationMailer.complete_mail(@user).deliver_now
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'コメント投稿に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  # コメント削除
  def destroy
    @comment = Comment.find_by(post_id: params[:post_id], user_id: current_user.id)
    @comment.destroy
    flash[:primary] = 'コメント削除しました'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.new(contcts_params)
    if @contact.save
      NotificationMailer.user_contact.deliver_now
      redirect_to(users_homes_my_page_path)
    else
      render(:new)
    end
  end

  private

  def contcts_params
    params.require(:contact).permit(:title, :contact_body)
  end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  def create
    @post = current_user.favorites.new(post_id: params[:post_id])
    @post.save ? redirect_back(fallback_location: root_path) : redirect_back(fallback_location: root_path)
  end

  def destroy
    if Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
      @favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
      @favorite.destroy
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top; end

  def about; end

  def my_page; end

  def guidance; end
end

app/controllers/users/notes_controller.rb
class Users::NotesController < ApplicationController
  before_action :note_information, only: [:edit, :update, :destroy]

  def index
    @note = Note.new
    @notes = current_user.notes
  end

  def create
    @note = current_user.notes.new(notes_params)
    if @note.save
      respond_to do |format|
        format.html { redirect_to(users_notes_path) }
        format.json
      end
    else
      @notes = current_user.notes
      render(:index)
    end
  end

  def edit
  end

  def update
    @note.update(notes_params) ? redirect_to(users_notes_path) : render(:edit)
  end

  def destroy
    @note.destroy ? redirect_to(users_notes_path) : render(:index)
  end

  private

  def notes_params
    params.require(:note).permit(:note_title, :note_body, :post_image)
  end

  def note_information
    @note = Note.find(params[:id])
  end
end

app/controllers/users/notices_controller.rb
class Users::NoticesController < ApplicationController
  def index
    @notices = Notice.all
  end

  def show
    @notice = Notice.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # skip_before_action :authenticate_user_from_token!, only: [:create,:update]

  def create
    user = User.find_by(email: create_params[:email])
    user&.send_reset_password_instructions
    render json: {}
  end

  def update
    user = User.reset_password_by_token(update_params)
    render json: user, status: :ok, serializer: V1::UserSerializer
  end

  private

  def create_params
    params.require(:user).permit(:email)
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :post_get_id, only: [:show, :edit, :update, :destroy]
  before_action :user_recent_post, only: [:index, :search, :create]
  before_action :post_new, only: [:index, :search]
  before_action :post_solution_search_false, only: [:index, :create]

  def index
  end

  def create
    @post = current_user.posts.new(posts_params)
    if @post.save
      flash[:primary] = '投稿が完了しました'
      respond_to do |format|
        format.html { redirect_to(users_posts_path) }
        format.json
      end
    else
      flash.now[:alert] = '投稿が失敗しました'
      render(:index)
    end
  end

  def show
    @comments = @post.comments.page(params[:page]).per(9)
    @comment = Comment.new
  end

  def update
    # 解決ボタンをクリックした場合
    if params[:solution]
      @post.solution = params[:solution]
      @post.update ? redirect_to(users_posts_path) : render(:show)
    end
    # お悩み内容を変更した場合
    @post.solution = false
    if @post.update(posts_params)
      flash[:primary] = '投稿内容を変更しました'
      redirect_to users_posts_path
    else
      flash.now[:alert] = '投稿内容の編集に失敗しました'
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:primary] = '投稿内容を削除しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = '投稿内容の削除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def search
    if params[:name]
      if params[:name].empty?
        @posts = Post.none.page(params[:page]).per(9)
      else
        @posts = Post.where('title LIKE(?)', "%#{params[:name]}%").recent.page(params[:page]).per(9)
      end
    else
      @posts = Post.recent.page(params[:page]).per(9)
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :post_body, :post_image, :solution)
  end

  def post_get_id
    @post = Post.find(params[:id])
  end

  def user_recent_post
    @users = User.recent_post
  end

  def post_new
    @post = Post.new
  end

  def post_solution_search_false
    @posts = Post.where(solution: false).recent.page(params[:page]).per(9)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  #   NotificationMailer.complete_mail(@user).deliver_now
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :my_page_infomration, only: [:show, :update]

  def show
    @solution_posts = Post.where(solution: true).recent.page(params[:page]).per(9)
  end

  def update
    if current_user.update(user_params)
      NotificationMailer.user_update(current_user).deliver_now
      flash[:primary] = 'ユーザー情報の変更が完了しました'
      redirect_to(users_users_path)
    else
      flash.now[:alert] = 'ユーザー情報の変更が失敗しました'
      render(:show)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def my_page_infomration
    @user = current_user
    @posts = current_user.posts.recent.page(params[:page]).per(9)
    @current_user_favorites = current_user.favorites_post.recent.page(params[:page]).per(9)
    @current_user_comments = current_user.comments_post.recent.page(params[:page]).per(9)
  end
end

app/controllers/users/youtube_controller.rb
class Users::YoutubeController < ApplicationController
  GOOGLE_API_KEY = ENV['Youtube_API']

  def find_videos(keyword, after: 1.months.ago, before: Time.now)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY

    next_page_token = nil
    opt = {
      q: keyword,
      type: 'video',
      max_results: 4,
      order: :date,
      page_token: next_page_token,
      published_after: after.iso8601,
      published_before: before.iso8601,
    }
    service.list_searches(:snippet, opt)
  end

  def index
    if params[:keyword]
      @youtube_data = find_videos(params[:keyword])
    end
    @youtube = Youtube.new
  end

  def create
    @youtube = current_user.youtubes.new(youtube_params)
    @youtube.save ? redirect_to(users_users_youtube_path) : render(:index)
  end

  def destroy
    @youtube = Youtube.find(params[:id])
    @youtube.destroy ? redirect_to(users_users_youtube_path) : render(:favorite)
  end

  def favorite
    @youtubes = current_user.youtubes.order(created_at: "DESC").page(params[:page]).per(15)
  end

  private

  def youtube_params
    params.require(:youtube).permit(:youtube_title, :youtube_comment, :youtube_url)
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/answers_helper.rb
module Users::AnswersHelper
end

app/views/users/homes/about.html.erb
<div class="jumbotron">
 <div class="container top pt-5">
   <div class="top-message">
     <h1>ようこそFashionInformation_appへ</h1>
     <p class="h3">さあ、毎日のファッションコーデを楽しくしていきましょう!</p>
     <div class="mt-4">
       <%= link_to '新規会員登録', new_user_registration_path,class: 'btn btn-success mr-3' %>
       <%= link_to 'ログイン', new_user_session_path,class: 'btn btn-primary' %>
     </div>
   </div>
 </div>
</div>
<div class="pt-3 pb-5 introduce top-p">
<h2 class="text-center mb-2 ">FashionInformation_appについて</h2>
  <h3 class=" text-center mt-2 mb-3">サービス内容</h3>
  <p class=" p-5 border border-secondary h5">
    みなさん、以下のようなご経験はございませんか？<br><br>
    ・洋服のコーディネートで悩んだことがあった。<br>
    ・洋服がほしいけど何を買えばいいのかがわからないことがあった。<br><br>
    もしこのようなご経験がある方はこのアプリで解消することができます。<br>
    このFashionInformation_appはファッションお悩み解消アプリです。<br>
    FashionInformation_appではファッションのお悩みの投稿しユーザー同士で解消する他<br>
    ,Youtubeのファッション情報を取得しお悩みの解決を手助けしてくれます。<br>
    さあ、FashionInformation_appでファッションの悩み事を解消していきましょう！
    これからよろしくお願い位いたします。
  </p>
</div>
<div class='top-Task pb-5 bg-white'>
  <h2 class="text-center pt-5 pb-5">FashionInformation_appでできること</h2>
  <div class="container-fluid">
    <div class="row ">
      <div class="col-lg-6 h4 mt-5">
        <ul>
          <li class = 'mb-3'>
            お悩みをアプリ内で投稿することができる
          </li>
          <li class = 'mb-3'>
            Youtubeの動画を取得し、ファッション情報を取得できる
          </li>
          <li class = 'mb-3'>
            ファッション情報を保存しいつでも見ることができる
          </li>
        </ul>
      </div>
      <div class="col-lg-6">
          <%= image_tag 'bruce-mars-AndE50aaHn4-unsplash.jpg',class: "about-image w-100 rounded " %>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid top-Task pb-5 bg-white">
  <h2 class="text-center mb-5">FashionInformation_appのご利用に向いている方</h2>
  <div class="row">
    <div class="col-lg-6">
      <%= image_tag 'umit-bulut-qbTC7ZwJB64-unsplash.jpg',class: "about-image w-100 rounded" %>
    </div>
    <div class="col-lg-6 h4 mt-5">
      <ul>
        <li class = 'mb-3'>
          毎日のコーディネートで悩んでいる方
        </li>
        <li class = 'mb-3'>
          ファッション情報が欲しい方
        </li>
        <li class = 'mb-3'>
          洋服が欲しいが、何を買えばいいのかわからない方
        </li>
      </ul>
    </div>
  </div>
</div>
<div>
<div class="container top-m-message text-center mb-5 pb-5">
  <h2 class=" mt-5 mb-5">さあ、FashionInformation_appを利用してみよう!</h2>
  <div class="row">
    <div class="col-6">
      <p class='h4'>初めて利用する方</p>
        <%= link_to '新規会員登録', new_user_registration_path,class: 'btn btn-success mr-3' %>
    </div>
    <div class="col-6">
      <p class='h4'>利用したことがある方</p>
        <%= link_to 'ログイン', new_user_session_path,class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/users/homes/guidance.html.erb
<div class="guidance">
  <div class="container mt-5 pt-5 mb-5 pb-5  text-center">
    <div>
      <h2>ご案内</h2>
      <p>
        ご登録ありがとうございます。<br>
        このページではこのアプリの操作方法をお伝えいたします。
      </p>
    </div>
    <div class="mt-5">
      <h3>アプリの使い方</h3>
      <p class='h5'>
        このアプリの使い方は主に２つございます。<br>
        １つ目は、ファッションに関してお悩み事をアプリに投稿し、ユーザー又は管理者でお悩みを解決することです。<br>
        ２つ目は、Youtube検索機能を使いファッション情報を動画で取得することです。
      </p>
    </div>
    <div class="mt-5">
      <h3>アプリの構成</h3>
      <p>このアプリは以下５つの機能がございます。</p>
      <ul class='h5 mb-5'>
        <li>
          お悩み投稿
        </li>
        <li>
          Youtube動画検索
        </li>
        <li>
          ユーザー情報
        </li>
        <li>
          お知らせ
        </li>
        <li>
          お問い合わせ
        </li>
      </ul>
    </div>
    <div class = 'guidance_content mb-5 p-5'>
      <h3 class="text-center mb-3">お悩み投稿</h3>
      <p>
        お悩み投稿はファッションに関するお悩み事をアプリに投稿することができる機能です。<br>
        投稿されたお悩み事に対して他のユーザーや管理者がコメントをし,お悩みを解決することができます。
        お悩み投稿者はいいコメントを行ったユーザーにgoodコメントポイントをあげることができます。
        このgoodコメントポイントは一週間毎に統計をとっており、ランキング上位者はお悩み一覧ページで確認することができます。
        ぜひあなたも、お悩みに対してコメントをしてあげてください。
        (ランキング上位者には特典を考察中です!)
      </p>
    </div>
    <div class = 'guidance_content mb-5 p-5'>
      <h3 class="text-center  mb-3">Youtube動画検索</h3>
      <p>
        Youtube動画検索機能は検索バーから任意のキーワードでYoutube動画を検索することができます<br>
        画像やニュースではなかなか着こなし方や最新トレンドを理解することが難しい時があると思いますので
        ぜひ、動画からファッション情報を取得してください。
        オススメのユーチューバーはメンズならげんじさん、ハズムさん、女性なら、プチプラのあやちゃんチャンネルをオススメいたします！
      </p>
    </div>
    <div class = 'guidance_content mb-5 p-5'>
      <h3 class="text-center mb-3">ユーザー情報</h3>
      <p>
        ユーザー情報機能はご登録された名前やemailの確認を行うことができます。
        また、過去に投稿したお悩み,ブックマークしたお悩み,コメントしたお悩みを確認することができます。
      </p>
    </div>
    <div class = 'guidance_content mb-5 p-5'>
      <h3 class="text-center mb-3">お知らせ</h3>
      <p>
        お知らせ機能は管理者からユーザーの方にお伝えしたいことを確認できる機能です。
        時々チェックしてみてください。
      </p>
    </div>
    <div class = 'guidance_content mb-5 p-5'>
      <h3 class="text-center mb-3">お問い合わせ</h3>
      <p>
        お問い合わせ機能は、管理者にこのアプリに対してお問い合わせすることができる機能です。
        退会に関することもこちらからよろしくお願いいたします。
      </p>
    </div>
  </div>

</div>

app/views/users/homes/my_page.html.erb
<div class="p-5 my-page">
  <div class="container">
    <%= render partial: "layouts/flash_message" %>
    <div class="row pt-5">
      <div class="col-lg-4 mb-5">
        <div class = "my-page-box p-5">
          <h3 class = "text-center mb-3 pb-2 border-bottom my-page-top">ご案内</h3>
          <div class="my-page-content">
            <p>このアプリの機能の説明をしてあります。ぜひご覧ください！</p>
            <%= link_to 'こちらをクリック',users_homes_guidance_path,class: 'my-page-link btn btn-outline-secondary' %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-5">
        <div class = " my-page-box p-5">
          <h3 class = "text-center mb-3 pb-2 border-bottom my-page-top">お悩み質問をする</h3>
          <div class="my-page-content">
            <p>ここではファッションに関するお悩みや疑問の質問を行うことができます。</p>
            <%= link_to 'こちらをクリック',users_posts_path,class: 'my-page-link btn btn-outline-secondary ' %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-5">
        <div class = "my-page-box p-5">
          <h3 class = "text-center mb-3 pb-2 border-bottom my-page-top">Youtube動画検索</h3>
          <div class="my-page-content">
            <p>ファッション系Youtuberから情報をGETしちゃおう!</p>
            <%= link_to 'こちらをクリック',users_youtube_index_path,class: 'my-page-link btn btn-outline-secondary' %>
          </div>
        </div>
      </div>
    </div>
    <div class="row pb-5">
      <div class="col-lg-4 mb-5">
        <div class = "my-page-box p-5">
          <h3 class = "text-center mb-3 pb-2 border-bottom my-page-top">ユーザー情報</h3>
          <div class="my-page-content">
            <p>ここではユーザー情報の確認編集を行うことができます。</p>
            <%= link_to 'こちらをクリック',users_users_path,class: 'my-page-link btn btn-outline-secondary' %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-5">
        <div class = "my-page-box p-5">
          <h3 class = "text-center mb-3 pb-2 border-bottom my-page-top">お知らせ</h3>
          <div class="my-page-content">
            <p>運営からお知らせが届くことがあります.........たまにはチェックしてね</p>
            <%= link_to 'こちらをクリック',users_notices_path,class: 'my-page-link btn btn-outline-secondary' %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-5">
        <div class = "my-page-box p-5">
          <h3 class = "text-center mb-3 pb-2 border-bottom my-page-top">お問い合わせ</h3>
          <div class="my-page-content">
            <p>運営にご意見がありましたらこちらまで</p>
            <%= link_to 'こちらをクリック',new_users_contact_path,class: 'my-page-link btn btn-outline-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/homes/top.html.erb
<div id="carouselOption1" class="carousel slide top-page" data-ride="carousel">
  <!-- インジケータの設定 -->
  <ol class="carousel-indicators">
    <li data-target="#carouselOption1" data-slide-to="0" class="active"></li>
    <li data-target="#carouselOption1" data-slide-to="1"></li>
    <li data-target="#carouselOption1" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'hannah-morgan-ycVFts5Ma4s-unsplash.jpg',class: "top-image d-block w-100 " %>
      <div class="carousel-caption d-none d-md-block">
        <h2>今日何を来ていけばいいのかわからなくなる時がありませんか?</h2>
      </div>
    </div>
    <div class="carousel-item ">
      <%= image_tag 'burgess-milner-OYYE4g-I5ZQ-unsplash.jpg',class:"top-image d-block w-100" %>
      <div class="carousel-caption d-none d-md-block">
        <h2>洋服で何を買えばいいのかわからない経験をしたことはありませんか？</h2>
      </div>
    </div>
    <div class="carousel-item ">
      <%= image_tag 'victor-garcia-3YW2jxSblE8-unsplash.jpg',class: "top-image d-block w-100" %>
      <div class="carousel-caption d-none d-md-block">
        <h2>このアプリではこのお悩みを解決できます!</h2>
      </div>
    </div>
  </div>
</div>

<div class = 'container mb-5 '>
  <div class="row text-center pt-5">
    <div class="col-lg-4 p-3">
      <h5 class="mb-3">このアプリを初めて利用される方</h5>
      <%= link_to '新規会員登録', new_user_registration_path,class: 'btn btn-primary' %>
    </div>
    <div class="col-lg-4 p-3">
      <h5 class="mb-3">既に会員登録済の方</h5>
      <%= link_to 'ログイン', new_user_session_path,class: 'btn btn-success' %>
    </div>
    <div class="col-lg-4 p-3">
      <h5 class="mb-3">アプリのことをよく知りたい方</h5>
      <%= link_to 'アプリ詳細', users_homes_about_path,class: 'btn btn-info' %>
    </div>
  </div>
</div>