config/routes.rb
Rails.application.routes.draw do
  root to: 'users/homes#top'

  # デバイスのURL
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get '/users/sign_in' => 'users/sessions#new'
    post '/users/sign_in' => 'users/sessions#create'
    delete '/users/sign_out' => 'users/sessions#destroy'
    get '/users/sign_up' => 'users/registrations#new'
    get '/users/passwords/edit' => 'users/registrations#edit'
    patch '/users/passwords/update' => 'users/registrations#update'
    post '/users/sign_up' => 'users/registrations#create'
    get '/users/' => 'users/passwords#edit'
    patch '/users/passwords' => 'users/passwords#update'
    get '/users/passwords/new' => 'users/passwords#new'
  end

  # ユーザー側のURL
  namespace :users do
    resource :passwords, only: [:create, :update]
    get 'homes/about' => 'homes#about'
    get 'homes/my_page' => 'homes#my_page'
    get 'homes/guidance' => 'homes#guidance'
    resource :users, only: [:show, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :youtube, only: [:index, :create, :destroy]
    resources :notes, only: [:index, :edit, :create, :destroy, :update]
    resources :notices, only: [:index, :show]
    get '/users/youtube' => '/users/youtube#favorite'
    resources :posts do
      resources :comments, only: [:create, :destroy] do
        resource :answers, only: [:create, :destroy]
      end
      resource :favorites, only: [:create, :destroy]
    end
    get '/users/posts' => '/users/posts#search'
  end

  # 管理者側のURL
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'

    authenticated :admin do
      delete '/admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
      get 'admins/password/edit' => 'admins/passwords#edit', as: 'edit_admin_password'
      patch 'admins/password' => 'admins/passwords#update', as: 'admin_password'
      get 'admins/passwords/new' => 'admins/password#new', as: 'admin_forgot_password'
    end
  end

  namespace :admins do
    resource :admins, only: [:show, :edit]
    resources :users, only: [:index, :edit, :destroy, :update]
    resources :posts, only: [:index, :edit, :destroy, :update]
    resources :contacts, only: [:index, :show, :destroy, :update]
    resources :notices, only: [:index, :edit, :update, :destroy, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :post_information, only: [:edit, :update, :destroy]

  def index
    @posts_solution = Post.where(solution: false).recent.page(params[:page]).per(20).search(params[:title])
    @posts = Post.recent.page(params[:page]).per(20).search(params[:title])
  end

  def edit
    @comments = @post.comments.page(params[:page]).per(9)
    @comment = Comment.new
  end

  def update
    @post.update(posts_params) ? redirect_to(dmins_posts_path) : render(:edit)
  end

  def destroy
    @post.destroy ? redirect_to(admins_posts_path) : render(:index)
  end

  private

  def posts_params
    params.require(:post).permit(:title, :post_body, :post_image)
  end

  def post_information
    @post = Post.find(params[:id])
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :user_information, only: [:edit, :update, :destroy]

  def index
    @users = User.recent.page(params[:page]).per(20).search(params[:name])
  end

  def edit
  end

  def update
    @user.update(user_params) ? redirect_to(admins_users_path) : render(:edit)
  end

  def destroy
    @user.destroy ? redirect_to(admins_users_path) : render(:index)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def user_information
    @user = User.find(params[:id])
  end
end

app/controllers/users/answers_controller.rb
class Users::AnswersController < ApplicationController
  # good_answer作成
  def create
    comment = Comment.find(params[:comment_id])
    @answer = Answer.new(comment_id: params[:comment_id], user_id: comment.user.id)
    if @answer.save
      user = User.find(comment.user.id)
      user.update(answer_point: user.answer_point += 1)
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  # good_answer消去
  def destroy
    comment = Comment.find(params[:comment_id])
    if Answer.find_by(comment_id: params[:comment_id], user_id: comment.user_id)
      @answer = Answer.find_by(comment_id: params[:comment_id], user_id: comment.user_id)
      @answer.destroy
      user = User.find(comment.user.id)
      user.update(answer_point: user.answer_point -= 1)
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  # コメント生成
  def create
    post = Post.find(params[:post_id])
    @user = post.user
    @comment = post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:primary] = 'コメント投稿を投稿しました'
      NotificationMailer.complete_mail(@user).deliver_now
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'コメント投稿に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  # コメント削除
  def destroy
    @comment = Comment.find_by(post_id: params[:post_id], user_id: current_user.id)
    @comment.destroy
    flash[:primary] = 'コメント削除しました'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.new(contcts_params)
    if @contact.save
      NotificationMailer.user_contact.deliver_now
      redirect_to(users_homes_my_page_path)
    else
      render(:new)
    end
  end

  private

  def contcts_params
    params.require(:contact).permit(:title, :contact_body)
  end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  def create
    @post = current_user.favorites.new(post_id: params[:post_id])
    @post.save ? redirect_back(fallback_location: root_path) : redirect_back(fallback_location: root_path)
  end

  def destroy
    if Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
      @favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
      @favorite.destroy
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top; end

  def about; end

  def my_page; end

  def guidance; end
end

app/controllers/users/notes_controller.rb
class Users::NotesController < ApplicationController
  before_action :note_information, only: [:edit, :update, :destroy]

  def index
    @note = Note.new
    @notes = current_user.notes
  end

  def create
    @note = current_user.notes.new(notes_params)
    if @note.save
      respond_to do |format|
        format.html { redirect_to(users_notes_path) }
        format.json
      end
    else
      @notes = current_user.notes
      render(:index)
    end
  end

  def edit
  end

  def update
    @note.update(notes_params) ? redirect_to(users_notes_path) : render(:edit)
  end

  def destroy
    @note.destroy ? redirect_to(users_notes_path) : render(:index)
  end

  private

  def notes_params
    params.require(:note).permit(:note_title, :note_body, :post_image)
  end

  def note_information
    @note = Note.find(params[:id])
  end
end

app/controllers/users/notices_controller.rb
class Users::NoticesController < ApplicationController
  def index
    @notices = Notice.all
  end

  def show
    @notice = Notice.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # skip_before_action :authenticate_user_from_token!, only: [:create,:update]

  def create
    user = User.find_by(email: create_params[:email])
    user&.send_reset_password_instructions
    render json: {}
  end

  def update
    user = User.reset_password_by_token(update_params)
    render json: user, status: :ok, serializer: V1::UserSerializer
  end

  private

  def create_params
    params.require(:user).permit(:email)
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :post_get_id, only: [:show, :edit, :update, :destroy]
  before_action :user_recent_post, only: [:index, :search, :create]
  before_action :post_new, only: [:index, :search]
  before_action :post_solution_search_false, only: [:index, :create]

  def index
  end

  def create
    @post = current_user.posts.new(posts_params)
    if @post.save
      flash[:primary] = '投稿が完了しました'
      respond_to do |format|
        format.html { redirect_to(users_posts_path) }
        format.json
      end
    else
      flash.now[:alert] = '投稿が失敗しました'
      render(:index)
    end
  end

  def show
    @comments = @post.comments.page(params[:page]).per(9)
    @comment = Comment.new
  end

  def update
    # 解決ボタンをクリックした場合
    if params[:solution]
      @post.solution = params[:solution]
      @post.update ? redirect_to(users_posts_path) : render(:show)
    end
    # お悩み内容を変更した場合
    @post.solution = false
    if @post.update(posts_params)
      flash[:primary] = '投稿内容を変更しました'
      redirect_to users_posts_path
    else
      flash.now[:alert] = '投稿内容の編集に失敗しました'
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:primary] = '投稿内容を削除しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = '投稿内容の削除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def search
    if params[:name]
      if params[:name].empty?
        @posts = Post.none.page(params[:page]).per(9)
      else
        @posts = Post.where('title LIKE(?)', "%#{params[:name]}%").recent.page(params[:page]).per(9)
      end
    else
      @posts = Post.recent.page(params[:page]).per(9)
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :post_body, :post_image, :solution)
  end

  def post_get_id
    @post = Post.find(params[:id])
  end

  def user_recent_post
    @users = User.recent_post
  end

  def post_new
    @post = Post.new
  end

  def post_solution_search_false
    @posts = Post.where(solution: false).recent.page(params[:page]).per(9)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  #   NotificationMailer.complete_mail(@user).deliver_now
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :my_page_infomration, only: [:show, :update]

  def show
    @solution_posts = Post.where(solution: true).recent.page(params[:page]).per(9)
  end

  def update
    if current_user.update(user_params)
      NotificationMailer.user_update(current_user).deliver_now
      flash[:primary] = 'ユーザー情報の変更が完了しました'
      redirect_to(users_users_path)
    else
      flash.now[:alert] = 'ユーザー情報の変更が失敗しました'
      render(:show)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def my_page_infomration
    @user = current_user
    @posts = current_user.posts.recent.page(params[:page]).per(9)
    @current_user_favorites = current_user.favorites_post.recent.page(params[:page]).per(9)
    @current_user_comments = current_user.comments_post.recent.page(params[:page]).per(9)
  end
end

app/controllers/users/youtube_controller.rb
class Users::YoutubeController < ApplicationController
  GOOGLE_API_KEY = ENV['Youtube_API']

  def find_videos(keyword, after: 1.months.ago, before: Time.now)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY

    next_page_token = nil
    opt = {
      q: keyword,
      type: 'video',
      max_results: 4,
      order: :date,
      page_token: next_page_token,
      published_after: after.iso8601,
      published_before: before.iso8601,
    }
    service.list_searches(:snippet, opt)
  end

  def index
    if params[:keyword]
      @youtube_data = find_videos(params[:keyword])
    end
    @youtube = Youtube.new
  end

  def create
    @youtube = current_user.youtubes.new(youtube_params)
    @youtube.save ? redirect_to(users_users_youtube_path) : render(:index)
  end

  def destroy
    @youtube = Youtube.find(params[:id])
    @youtube.destroy ? redirect_to(users_users_youtube_path) : render(:favorite)
  end

  def favorite
    @youtubes = current_user.youtubes.order(created_at: "DESC").page(params[:page]).per(15)
  end

  private

  def youtube_params
    params.require(:youtube).permit(:youtube_title, :youtube_comment, :youtube_url)
  end
end

app/views/users/posts/_form_post.html.erb
<h2 class = "mb-3 mt-3 ">お悩み投稿</h2>
<%= form_with(model:post,url: users_posts_path, method: :post) do |f| %>

<!-- エラーメッセージ表示-->
<% if post.errors.any? %>
<h3><%= post.errors.count %>件のエラーが発生</h3>
<ul>
  <% post.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<!-- ユーザー情報表示-->
  <div>
    <%= f.label :'タイトル' %><br>
    <%= f.text_field :title,class:'form-control',id:'post_title' %>
  </div>

  <div class="mt-4">
    <%= f.label :'画像' %><br/>
    <%= f.attachment_field :post_image,id:'post_image' %>
  </div>

  <div class="mt-4 ">
    <%= f.label :'本文' %><br/>
    <%= f.text_area :post_body,class:'form-control',id:'post_body' %>
  </div>

<div class="mt-4">
  <%= f.submit "投稿する",class: 'btn btn-info post_submit'%>
</div>

<% end %>

app/views/users/posts/_posts_index.html.erb
<%# ランキングに必要な変数 %>
  <% rank = 0 %>

<ul id="tab-menu-post" class="clearfix">
  <li><a href="#tab1" class="active">お悩み一覧</a></li>
  <li><a href="#tab2" class="">Good コメントランキング</a></li>
</ul>

<div id="tab-contents" class="clearfix">
  <div id="tab1" class="tab">
    <div class="row" id='post_card'>
     <% posts.each do |post| %>
      <div class="col-lg-4 mb-3">
        <div class="card">
         <%= attachment_image_tag(post,:post_image, fallback: "no_image.jpg", size:'300x350' ,class:"card-img-top") %>
           <div class="card-body">
            <%= post.title %>
            <p class = 'class='card-text''>
              <%= post.created_at.to_s(:datetime_jp) %><br>
              <%= "コメント数 : #{post.comments.count}" %><br>
              <%= link_to 'お悩みを解決する',users_post_path(post),class: 'btn btn-outline-dark'%><br>
              <% if post.favorites_user(current_user.id, post.id) %>
               <%= link_to 'ブックマーク解除',users_post_favorites_path(post),method: :delete,class: 'btn btn-outline-danger' %><br>
              <% else %>
               <%= link_to 'ブックマーク',users_post_favorites_path(post),method: :post,class: 'btn btn-outline-dark' %><br>
              <% end %>
              <% if post.user_id == current_user.id %>
               <%= link_to '編集',edit_users_post_path(post),class: 'btn btn-outline-success' %>
               <%= link_to '削除',users_post_path(post),method: :delete, data: {confirm: "削除しますか？"},class: 'btn btn-outline-danger' %>
              <% end %>
            </p>
           </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class='mb-5'>
      <%= paginate posts %>
    </div>
  </div>
  <div id="tab2" class="tab">
    <div class="row" id='post_card'>
        <p>
          この一覧はお悩みに対して良いコメントをした方のランキングです。
          さあ、お悩みを解決してください!
        </p>
      <% users.each do |user| %>
      <table class = "table">
        <thead>
          <tr>
            <th>順位</th><th>ユーザー名</th><th>Good コメント数</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= rank += 1 %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= user.answer_point %>
            </td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/posts/_search_post.html.erb
<!-- 検索フォーム -->
<div class='text-center mb-5'>
  <div class="row justify-content-center ">
    <div>
      <%= form_with(url: users_users_posts_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :name, placeholder: "検索", class: "search-inputa form-control",id: 'search-input', autocomplete:'off' %>
    </div>
    <div>
      <%= f.submit '検索',class: 'btn btn-info ml-3 '%>
    </div>
    <% end %>
  </div>
  <div class="result">
    <ul>
      <!-- この中にインクリメンタルサーチの結果が表示される -->
    </ul>
  </div>
</div>

app/views/users/posts/edit.html.erb
<div class="container pt-5 mt-5">
  <!-- flash_messageを表示 -->
  <%= render partial: "layouts/flash_message" %>
  
  <h2>詳細</h2>
  <%= form_for(@post,url:users_post_path(@post) , method: :PATCH) do |f| %>

  <!-- エラーメッセージ表示-->
  <% if @post.errors.any? %>
  <h3><%= @post.errors.count %>件のエラーが発生</h3>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <!-- ユーザー情報表示-->
  <div class="row">
    <div class="col">
      <%= f.label :'タイトル' %><br>
      <%= f.text_field :title,class:'form-control' %>
    </div>

    <div class="col">
      <%= f.label :'本文' %><br/>
      <%= f.text_area :post_body,class:'form-control ', rows: 5 %>
    </div>
  </div>

  <div class="mt-4">
    <%= f.label :'画像' %><br/>
    <%= f.attachment_field :post_image %>
  </div>

  <div class="mt-4">
    <%= f.submit "保存",class: 'btn btn-info mr-3'%>
    <%= link_to '戻る',users_posts_path,class: 'btn btn-info' %>
  </div>

  <% end %>
</div>

app/views/users/posts/index.html.erb
<div class="mt-5 pt-5 pb-5 mb-5 container">
  <!-- flash_messageを表示 -->
  <%= render partial: "layouts/flash_message" %>

  <h2 class = 'text-center mt-3 mb-3'>お悩み一覧</h2>
  <p class = 'text-center'>この検索バーからは現在投稿されているお悩みを探すことができます。</p>

  <!-- 検索フォーム -->
  <%= render partial: "search_post" %>

  <div class="row">
    <div class="col-lg-3 order-lg-1">
      <%# 投稿フォーム %>
      <%= render partial: "form_post", locals: { post: @post }%>
    </div>

    <div class="col-lg-9 wrap order-lg-2">
      <%= render partial: "posts_index", locals: { posts: @posts, users: @users } %>
    </div>
  </div>
</div>

app/views/users/posts/search.html.erb
<div class="pt-5 pb-5 mt-5 mb-5 container">
  <h2 class = 'text-center mt-3 mb-3'>検索結果</h2>
  <p class = 'text-center'>この検索バーからは現在投稿されているお悩みを探すことができます。</p>

  <!-- 検索フォーム -->
  <%= render partial: "search_post" %>

  <div class="row">
    <div class="col-lg-3 order-lg-1">
      <%# 投稿フォーム %>
      <%= render partial: "form_post", locals: { post: @post }%>
    </div>

    <div class="col-lg-9 wrap order-lg-2">
      <%= render partial: "posts_index", locals: { posts: @posts, users: @users } %>
    </div>
  </div>
</div>

app/views/users/posts/show.html.erb
<div class="container mt-5 pt-5 pb-5 mb-5">
  <!-- flash_messageを表示 -->
  <%= render partial: "layouts/flash_message" %>
  
  <h2 class = 'text-center mt-3 mb-3'>コメント</h2>
  <div class="row">
    <div class="col-lg-3 mb-5">
      <div class="card">
        <%= attachment_image_tag(@post,:post_image, fallback: "no_image.jpg",size:'300x350',class:"card-img-top") %>
        <div class="card-body">
          <h3>質問内容</h3>
          <div class="card-text">
            <p>
              質問者<br>
              <%= @post.user.name %>
            </p>
            <p>
              タイトル<br>
              <%= @post.title %>
            </p>
            <p>
              本文<br>
              <%= @post.post_body %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-9">
      <h5>コメント一覧</h5>
      <% @comments.each do |comments| %>
      <div class="border p-3 mb-3 bg-white">
        <div class="comment">
          <%= "#{comments.user.name}さんからのコメント" %><br>
          <%= comments.content %>
        </div>
        <div>
          <%# コメント削除 %>
          <% if comments.user_id == current_user.id %>
            <%= link_to '削除',users_post_comment_path(@post),method: :delete, data: {confirm: "削除しますか？"},class: 'btn btn-outline-danger mt-3' %>
          <% end %>
          <%# ベストアンサー機能 %>
          <% if current_user.id == @post.user_id %>
            <% if current_user.id != comments.user_id %>
              <% if comments.answers_user(comments.user_id,comments.id) %>
                <%= link_to 'bad Answer',users_post_comment_answers_path(@post,comments),method: :delete %>
              <% else %>
                <%= link_to 'Good Answer',users_post_comment_answers_path(@post,comments),method: :post %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        </div>
        <% end %>
        <div class='mb-5'>
          <%= paginate @comments %>
        </div>
        <h5>コメント投稿</h5>
          <%= form_for([@post, @comment] ,url:users_post_comments_path(@post),method: :post) do |f| %>
            <%= f.text_area :content, class: "form-control", rows: 5 %>
            <%= f.submit "投稿", class: "btn btn-info mt-3" %>
          <% end %>
          <% if current_user.id == @post.user_id %>
            <% if @post.solution == false %>
              <% @post.solution = true %>
              <%= form_for(@post, url: users_post_path(@post), method: :PATCH) do |f| %>
                <%= f.hidden_field :solution, :value => @post.solution %>
                <%= f.submit "お悩み解決",class: 'btn btn-success mt-3' %>
              <% end %>
            <% end %>
          <% end %>
  </div>
</div>