config/routes.rb
Rails.application.routes.draw do
  root to: 'users/homes#top'

  # デバイスのURL
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get '/users/sign_in' => 'users/sessions#new'
    post '/users/sign_in' => 'users/sessions#create'
    delete '/users/sign_out' => 'users/sessions#destroy'
    get '/users/sign_up' => 'users/registrations#new'
    get '/users/passwords/edit' => 'users/registrations#edit'
    patch '/users/passwords/update' => 'users/registrations#update'
    post '/users/sign_up' => 'users/registrations#create'
    get '/users/' => 'users/passwords#edit'
    patch '/users/passwords' => 'users/passwords#update'
    get '/users/passwords/new' => 'users/passwords#new'
  end

  # ユーザー側のURL
  namespace :users do
    resource :passwords, only: [:create, :update]
    get 'homes/about' => 'homes#about'
    get 'homes/my_page' => 'homes#my_page'
    get 'homes/guidance' => 'homes#guidance'
    resource :users, only: [:show, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :youtube, only: [:index, :create, :destroy]
    resources :notes, only: [:index, :edit, :create, :destroy, :update]
    resources :notices, only: [:index, :show]
    get '/users/youtube' => '/users/youtube#favorite'
    resources :posts do
      resources :comments, only: [:create, :destroy] do
        resource :answers, only: [:create, :destroy]
      end
      resource :favorites, only: [:create, :destroy]
    end
    get '/users/posts' => '/users/posts#search'
  end

  # 管理者側のURL
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'

    authenticated :admin do
      delete '/admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
      get 'admins/password/edit' => 'admins/passwords#edit', as: 'edit_admin_password'
      patch 'admins/password' => 'admins/passwords#update', as: 'admin_password'
      get 'admins/passwords/new' => 'admins/password#new', as: 'admin_forgot_password'
    end
  end

  namespace :admins do
    resource :admins, only: [:show, :edit]
    resources :users, only: [:index, :edit, :destroy, :update]
    resources :posts, only: [:index, :edit, :destroy, :update]
    resources :contacts, only: [:index, :show, :destroy, :update]
    resources :notices, only: [:index, :edit, :update, :destroy, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # アソシエーション
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  attachment :post_image

  # バリデーション
  validates :title, presence: true
  validates :post_body, presence: true

  # 最近のお悩み情報の取得の方法
  scope :recent, -> { order(created_at: "DESC") }

  # post情報取得scope
  scope :recent_post, -> { order(answer_point: "DESC").limit(3) }

  # お気に入りしているのかチェックメゾット
  def favorites_user(user_id, post_id)
    Favorite.where(user_id: user_id, post_id: post_id).exists?
  end

  # good_answerしているのかのチェックメゾット
  def answers_user(user_id, cooment_id)
    Answer.where(user_id: user_id, cooment_id: cooment_id).exists?
  end

  # 検索メゾット
  def self.search(search)
    return Post.all unless search
    Post.where(['title LIKE ?', "%#{search}%"])
  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :post_information, only: [:edit, :update, :destroy]

  def index
    @posts_solution = Post.where(solution: false).recent.page(params[:page]).per(20).search(params[:title])
    @posts = Post.recent.page(params[:page]).per(20).search(params[:title])
  end

  def edit
    @comments = @post.comments.page(params[:page]).per(9)
    @comment = Comment.new
  end

  def update
    @post.update(posts_params) ? redirect_to(dmins_posts_path) : render(:edit)
  end

  def destroy
    @post.destroy ? redirect_to(admins_posts_path) : render(:index)
  end

  private

  def posts_params
    params.require(:post).permit(:title, :post_body, :post_image)
  end

  def post_information
    @post = Post.find(params[:id])
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :post_get_id, only: [:show, :edit, :update, :destroy]
  before_action :user_recent_post, only: [:index, :search, :create]
  before_action :post_new, only: [:index, :search]
  before_action :post_solution_search_false, only: [:index, :create]

  def index
  end

  def create
    @post = current_user.posts.new(posts_params)
    if @post.save
      flash[:primary] = '投稿が完了しました'
      respond_to do |format|
        format.html { redirect_to(users_posts_path) }
        format.json
      end
    else
      flash.now[:alert] = '投稿が失敗しました'
      render(:index)
    end
  end

  def show
    @comments = @post.comments.page(params[:page]).per(9)
    @comment = Comment.new
  end

  def update
    # 解決ボタンをクリックした場合
    if params[:solution]
      @post.solution = params[:solution]
      @post.update ? redirect_to(users_posts_path) : render(:show)
    end
    # お悩み内容を変更した場合
    @post.solution = false
    if @post.update(posts_params)
      flash[:primary] = '投稿内容を変更しました'
      redirect_to users_posts_path
    else
      flash.now[:alert] = '投稿内容の編集に失敗しました'
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:primary] = '投稿内容を削除しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = '投稿内容の削除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def search
    if params[:name]
      if params[:name].empty?
        @posts = Post.none.page(params[:page]).per(9)
      else
        @posts = Post.where('title LIKE(?)', "%#{params[:name]}%").recent.page(params[:page]).per(9)
      end
    else
      @posts = Post.recent.page(params[:page]).per(9)
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :post_body, :post_image, :solution)
  end

  def post_get_id
    @post = Post.find(params[:id])
  end

  def user_recent_post
    @users = User.recent_post
  end

  def post_new
    @post = Post.new
  end

  def post_solution_search_false
    @posts = Post.where(solution: false).recent.page(params[:page]).per(9)
  end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/views/admins/posts/edit.html.erb
<div class="container pt-3 mt-5">
  <h2 class = 'text-center mt-3 mb-3'>コメント</h2>
  <div class="row">
    <div class="col-lg-3 mb-5">
      <div class="card">
        <%= attachment_image_tag(@post,:post_image, fallback: "no_image.jpg",class:"card-img-top") %>
        <div class="card-body">
          <h3>質問内容</h3>
          <div class="card-text">
            <p>
              質問者<br>
              <%= @post.user.name %>
            </p>
            <p>
              タイトル<br>
              <%= @post.title %>
            </p>
            <p>
              本文<br>
              <%= @post.post_body %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-9">
      <h5>コメント一覧</h5>
      <% @comments.each do |comments| %>
      <div class="border p-3 mb-3">
        <div class="comment">
          <%= "#{comments.user.name}さんからのコメント" %><br>
          <%= comments.content %>
        </div>
        <div>
          <%# コメント削除 %>
            <%= link_to '削除',users_post_comment_path(@post),method: :delete, data: {confirm: "削除しますか？"},class: 'btn btn-outline-danger mt-3' %>
          <%# ベストアンサー機能 %>
            <% if comments.answers_user(comments.user_id,comments.id) %>
              <%= link_to 'bad Answer',users_post_comment_answers_path(@post,comments),method: :delete,class: 'btn btn-outline-danger mt-3 ml-3' %>
            <% else %>
              <%= link_to 'Good Answer',users_post_comment_answers_path(@post,comments),method: :post,class: 'btn btn-outline-success mt-3 ml-3' %>
            <% end %>
        </div>
        </div>
        <% end %>
        <div class='mb-5'>
          <%= paginate @comments %>
        </div>
        <h5>コメント投稿</h5>
        <% @post.solution = true %>
        <%= form_for(@post, url: users_post_path(@post), method: :PATCH) do |f| %>
          <%= f.hidden_field :solution, :value => @post.solution %>
        <%= f.submit "お悩み解決",class: 'btn btn-success mt-3' %>
        <% end %>
  </div>
</div>

app/views/admins/posts/index.html.erb
<div class="container mb-5 pt-5 mb-5 pb-5">
  <h2 class ='text-center mt-5 mb-3'>お悩み一覧</h2>
  <!-- 検索フォーム -->
  <div class='text-center mb-5'>
    <div class="row justify-content-center ">
      <div>
        <%= form_tag(admins_posts_path,:method => 'get') do %>
        <%= text_field_tag :title %>
      </div>
      <div>
        <%= submit_tag '検索',class: 'btn btn-info ml-3 '%>
      </div>
      <% end %>
    </div>
  </div>
  <div class="wrap">
    <ul id="tab-menu-post" class="clearfix">
      <li><a href="#tab1" class="active">解決していないお悩み</a></li>
      <li><a href="#tab2" class="">解決したお悩み</a></li>
    </ul>
    <div id="tab-contents" class="clearfix">
      <div id="tab1" class="tab">
        <table class = 'table'>
          <thead>
            <tr>
              <th>タイトル<br>ユーザー名</th><th>ユーザー名</th><th>投稿日</th>
            </tr>
          </thead>
          <tbody>
            <% @posts_solution.each do |posts_solution| %>
            <tr>
              <th>
                <%= "タイトル : #{posts_solution.title}" %><br><br>
                <%= "ユーザー名 : #{posts_solution.user.name}" %><br><br>
                <%= "コメント数 : #{posts_solution.comments.count}" %>
              </th>
              <th>
                <%= link_to '詳細',edit_admins_post_path(posts_solution),class: 'btn btn-outline-info mb-3'%><br>
                <%= link_to '削除',admins_post_path(posts_solution),method: :delete, data: {confirm: "削除しますか？"},class: 'btn btn-outline-danger'%>
              </th>
              <th><%= posts_solution.created_at.to_s(:datetime_jp)  %></th>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class='mb-5'>
          <%= paginate @posts_solution %>
        </div>
      </div>
      <div id="tab2" class="tab">
        <table class = 'table'>
          <thead>
            <tr>
              <th>タイトル<br>ユーザー名</th><th>ユーザー名</th><th>投稿日</th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |posts| %>
            <tr>
              <th>
                <%= "タイトル : #{posts.title}" %><br><br>
                <%= "ユーザー名 : #{posts.user.name}" %><br><br>
                <%= "コメント数 : #{posts.comments.count}" %>
              </th>
              <th>
                <%= link_to '詳細',edit_admins_post_path(posts),class: 'btn btn-outline-info mb-3'%><br>
                <%= link_to '削除',admins_post_path(posts),method: :delete, data: {confirm: "削除しますか？"},class: 'btn btn-outline-danger'%>
              </th>
              <th><%= posts.created_at.to_s(:datetime_jp)  %></th>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class='mb-5'>
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>




</div>