config/routes.rb
Rails.application.routes.draw do
  root to: 'users/homes#top'

  # デバイスのURL
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get '/users/sign_in' => 'users/sessions#new'
    post '/users/sign_in' => 'users/sessions#create'
    delete '/users/sign_out' => 'users/sessions#destroy'
    get '/users/sign_up' => 'users/registrations#new'
    get '/users/passwords/edit' => 'users/registrations#edit'
    patch '/users/passwords/update' => 'users/registrations#update'
    post '/users/sign_up' => 'users/registrations#create'
    get '/users/' => 'users/passwords#edit'
    patch '/users/passwords' => 'users/passwords#update'
    get '/users/passwords/new' => 'users/passwords#new'
  end

  # ユーザー側のURL
  namespace :users do
    resource :passwords, only: [:create, :update]
    get 'homes/about' => 'homes#about'
    get 'homes/my_page' => 'homes#my_page'
    get 'homes/guidance' => 'homes#guidance'
    resource :users, only: [:show, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :youtube, only: [:index, :create, :destroy]
    resources :notes, only: [:index, :edit, :create, :destroy, :update]
    resources :notices, only: [:index, :show]
    get '/users/youtube' => '/users/youtube#favorite'
    resources :posts do
      resources :comments, only: [:create, :destroy] do
        resource :answers, only: [:create, :destroy]
      end
      resource :favorites, only: [:create, :destroy]
    end
    get '/users/posts' => '/users/posts#search'
  end

  # 管理者側のURL
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'

    authenticated :admin do
      delete '/admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
      get 'admins/password/edit' => 'admins/passwords#edit', as: 'edit_admin_password'
      patch 'admins/password' => 'admins/passwords#update', as: 'admin_password'
      get 'admins/passwords/new' => 'admins/password#new', as: 'admin_forgot_password'
    end
  end

  namespace :admins do
    resource :admins, only: [:show, :edit]
    resources :users, only: [:index, :edit, :destroy, :update]
    resources :posts, only: [:index, :edit, :destroy, :update]
    resources :contacts, only: [:index, :show, :destroy, :update]
    resources :notices, only: [:index, :edit, :update, :destroy, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :comment

  # good_answerしているのかのチェックメゾット
  def answers_user(user_id, comment_id)
    Answer.where(user_id: user_id, comment_id: comment_id).exists?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :post
  has_many :answers, dependent: :destroy

  # バリデーション
  validates :content, presence: true

  # good_answerしているのかのチェックメゾット
  def answers_user(user_id, comment_id)
    Answer.where(user_id: user_id, comment_id: comment_id).exists?
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  # アソシエーション
  belongs_to :user

  # バリデーション
  validates :title, presence: true
  validates :contact_body, presence: true

  # 最近のお悩み情報の取得の方法
  scope :recent, -> { order(created_at: "DESC") }

  # 検索メゾット
  def self.search(search)
    return Contact.all unless search
    Contact.where(['title LIKE ?', "%#{search}%"])
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :post
  validates :user_id, { presence: true }
  validates :post_id, { presence: true }
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  # アソシエーション
  belongs_to :user
  attachment :post_image

  # バリデーション
  validates :note_title, presence: true
  validates :note_body, presence: true
end

app/models/notice.rb
class Notice < ApplicationRecord
  # バリデーション
  validates :announce_title, presence: true
  validates :announce_body, presence: true

  # 最近のお悩み情報の取得の方法
  scope :recent, -> { order(created_at: "DESC") }

  # 検索メゾット
  def self.search(search)
    return Notice.all unless search
    Notice.where(['announce_title LIKE ?', "%#{search}%"])
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # アソシエーション
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  attachment :post_image

  # バリデーション
  validates :title, presence: true
  validates :post_body, presence: true

  # 最近のお悩み情報の取得の方法
  scope :recent, -> { order(created_at: "DESC") }

  # post情報取得scope
  scope :recent_post, -> { order(answer_point: "DESC").limit(3) }

  # お気に入りしているのかチェックメゾット
  def favorites_user(user_id, post_id)
    Favorite.where(user_id: user_id, post_id: post_id).exists?
  end

  # good_answerしているのかのチェックメゾット
  def answers_user(user_id, cooment_id)
    Answer.where(user_id: user_id, cooment_id: cooment_id).exists?
  end

  # 検索メゾット
  def self.search(search)
    return Post.all unless search
    Post.where(['title LIKE ?', "%#{search}%"])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :omniauthable, omniauth_providers: %i(google)

  # アソシエーション
  has_many :posts, dependent: :destroy
  has_many :youtubes, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :comments_post, through: :comments, source: :post
  has_many :favorites, dependent: :destroy
  has_many :favorites_post, through: :favorites, source: :post
  has_many :notes, dependent: :destroy
  has_many :answers, dependent: :destroy

  # バリデーション
  validates :name, presence: true
  validates :email, presence: true

  # 最近のお悩み情報の取得の方法
  scope :recent, -> { order(created_at: "DESC") }

  # post情報取得scope
  scope :recent_post, -> { order(answer_point: "DESC").limit(3) }

  # GoogleAPIメゾット

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    user ||= User.create(
      name: auth.info.name,
      provider: auth.provider,
      uid: auth.uid,
      token: auth.credentials.token,
      email: auth.info.email,
      password: Devise.friendly_token[0, 20],
      meta: auth.to_yaml
    )
    user
  end

  # 検索メゾット
  def self.search(search)
    return User.all unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end
end

app/models/youtube.rb
class Youtube < ApplicationRecord
  # アソシエーション
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admins_admins_path
    else
      users_homes_my_page_path
    end
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    if resource.is_a?(Admin)
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/notes_helper.rb
module Users::NotesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/admins/show.html.erb
<div class="container mb-5 pb-5">
  <h2 class ='text-center mt-3 mb-3'>My Page</h2>
  <div class="row pt-3 justify-content-between">
    <div class="col-lg-6 pb-5">
      <div class="card">
        <%= image_tag 'hannah-morgan-ycVFts5Ma4s-unsplash.jpg',class: 'card-img-top'%>
        <div class="card-body">
          <h3 class='card-title'>ユーザー情報一覧</h3>
          <p class='card-text'>
            <%= "現在の登録者人数は#{@users}人" %><br>
            <%= "本日の登録者人数は#{@today_registrations}人" %><br>
            <%= link_to 'ユーザー情報',admins_users_path,class: 'mt-3 btn btn-info' %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-6 pb-5">
      <div class="card ">
        <%= image_tag 'burgess-milner-OYYE4g-I5ZQ-unsplash.jpg',class: 'card-img-top'%>
        <div class="card-body">
          <h3 class='card-title'>質問情報一覧</h3>
          <p class='card-text'>
            <%= "現在のお悩み数は#{@posts_solution}です" %><br>
            <%= "合計お悩み数は#{@posts.count}です" %><br>
            <%= link_to '質問情報一覧',admins_posts_path,class: 'mt-3 btn btn-primary' %>
          </p>
        </div>
      </div>
    </div>
   </div>
  <div class="row pt-3 justify-content-between">
    <div class="col-lg-6 pb-5">
      <div class="card">
        <%= image_tag 'vadim-sherbakov-tCICLJ5ktBE-unsplash.jpg',class: 'card-img-top'%>
        <div class="card-body">
          <h3 class='card-title'>お知らせ一覧</h3>
          <p class='card-text'>
            <%= "投稿したお知らせ数は#{@notice.count}です" %><br><br>
            <%= link_to 'お知らせ情報',admins_notices_path,class: 'mt-3 btn btn-success' %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-6 pb-5">
      <div class="card">
        <%= image_tag 'umit-bulut-qbTC7ZwJB64-unsplash.jpg',class: 'card-img-top'%>
        <div class="card-body">
          <h3 class='card-title'>お問い合わせ一覧</h3>
          <p class='card-text'>
            <%= "解決していないお問い合わせ数は#{@contacts_solution}です" %><br>
            <%= "合計お問い合わせ数は#{@contacts.count}です" %><br>
            <%= link_to 'お問い合わせ情報',admins_contacts_path,class: 'mt-3 btn btn-success' %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>